# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
#  app:
#    build:
#      context: .
#      target: final
#    ports:
#      - 8080:8080
  websocket-stream-sink:
    image: springcloudstream/websocket-sink-rabbit:latest
    container_name: geo-stream-websocket-sink
    environment:
      - SERVER_PORT=8096
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION=geo-exchange
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_GROUP=ephemeral-geo
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONTENT_TYPE=application/json
      - SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONTENT_BINDER=rabbit
      - SPRING_CLOUD_STREAM_RABBIT_BINDINGS_INPUT_CONSUMER_QUEUE_NAME_GROUP_ONLY=true
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_TYPE=rabbit
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_ENVIRONMENT_SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_ENVIRONMENT_SPRING_RABBITMQ_USERNAME=guest
      - SPRING_CLOUD_STREAM_BINDERS_RABBIT_ENVIRONMENT_SPRING_RABBITMQ_PASSWORD=guest
    ports:
      - "8096:8096"
      - "9292:9292"
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
    ports:
      - "5552:5552"
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker-rabbit-enabled_plugins:/etc/rabbitmq/enabled_plugins
